### ISSUE TITLE
Vignette build not working

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.monitoring#2]
Despite fixing deprecated warning during vignette build in kwb.base (https://github.com/KWB-R/kwb.base/commit/0614b9333031c550edd74243e2464f5420c45dbb) there is another problem during vignette build:

> Error in getPredictionOfQ(hydraulicData = hydraulicData, regressionModels = regressionModels,  : 
> There is no such regression model: REGRESSION_DIR/ALT_01_regressionModel.txt.
> You may run section "Find H-Q regression to create such a model.
> Calls: withCallingHandlers ... .f -> render_rmarkdown -> <Anonymous> -> get_result
>Execution halted
>Error in getPredictionOfQ(hydraulicData = hydraulicData, regressionModels = regressionModels,  : 
> There is no such regression model: REGRESSION_DIR/ALT_01_regressionModel.txt.
>You may run section "Find H-Q regression to create such a model.

See also: https://travis-ci.org/KWB-R/kwb.monitoring/builds/394901117

**Comment by hsonne** [comment]
Everything that is leading to an error due to missing data is commented out now
